version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: smartgym
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - myNetwork

  db:
    image: postgres:13.1-alpine
    container_name: gym_db
    restart: always
    environment:
      POSTGRES_USER: cami
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: academia
    volumes:
      # Data
      - db-data:/var/lib/postresql/data
      # Scripts
      # - .docker/scripts:/scripts
      - ./docker/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge

volumes:
  db-data: